### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by kofno** [crystal-lang/heroku-buildpack-crystal#10]
`Deprecation: The compile command was renamed to build and will be removed in a future version.`

**Comment by zamith** [comment]
Thanks for report this. Do you know where we can find more information about that?

**Comment by bcardiff** [comment]
I did https://github.com/crystal-lang/heroku-buildpack-crystal/commit/a4e5d66f26e929d36624539df74f747be10b5491 to get rid of the warning but after that we dicided to rollback the build/compile change in crystal compiler. I was sure i rolled back that change. That will bring up warnings in some versions, but otherwise the code of the buildpack will be awful for nothing. Rolling back should do. I will do it as soon as i get in the computer.

**Comment by bcardiff** [comment]
fixed at 6ff3defa8d358810c194ff98f2c2db17e5dc5edb
