### ISSUE TITLE
LLVM 3.5

### ISSUE THREAD

**Issue by crisward** [crystal-lang/heroku-buildpack-crystal#21]
Inside the build pack

```
crystal -v
Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0
```
I'm getting very slow compile times, possibly because of this. Any ideas how I update this.

I'll update this if I work it out sooner.

**Comment by mverzilli** [comment]
I'm not sure if the slow compile times are due to that, but we already know LLVM 3.5 generates incorrect code and are in the process of dropping support for it. 

The Crystal version we use is here:

https://github.com/crystal-lang/heroku-buildpack-crystal/blob/master/bin/compile#L50

That is generated from https://github.com/crystal-lang/omnibus-crystal. There's already a WIP PR to move to LLVM 3.8 here: https://github.com/crystal-lang/omnibus-crystal/pull/17

So this issue should be fixed once we merge that PR. If you're in a hurry, I guess you could try to build Crystal from source, publish it, fork this repo and change that line. 

Hope this helps!

**Comment by crisward** [comment]
Thanks, it does help. I'm already using a fork of the buildpack with a variation of libgc, so I may create / link my own binary and see if it effects compile time.

Thanks again for the prompt response...

**Comment by mverzilli** [comment]
Cool! If it's not too much to ask, would you let us know how it goes? Would be useful to close the loop.

**Comment by crisward** [comment]
Quick update, I gave this a go but the crystal I built on ubuntu 14.04 against llvm 3.8 through errors when I tried to build my app. Think I missed something along the way. Hopefully I'll get another chance to try this week. I should have noted down the errors, but it was one of those '2:00am, give up and go to bed' moments. I'll be a bit more systematic in my process next time.

**Comment by crisward** [comment]
Its now impossible to compile in this buildpack with the lastest crystal as the 0.23 version required LLVM3.8>. 

Looks like I'm stuck on 0.22 until this is resolved. See other discussion here - https://github.com/crystal-lang/crystal/issues/4647

**Comment by mverzilli** [comment]
@crisward, thanks for keeping us up to date. Don't worry about "getting stuck", we will not release any new Crystal versions until there's a 0.23.x that works on Ubuntu 14.04.

**Comment by crisward** [comment]
Thanks, that's very reassuring.

**Comment by mverzilli** [comment]
@crisward I think this is no longer an issue, is it ok if we close it?

**Comment by crisward** [comment]
0.23.1 is compiled against 3.8, which sort of fixes this, however this has nothing really to do with the buildpack and more to do with the omnibus binaries. So I'll close. Thanks.
